#!/bin/sh

[ -f /var/lib/partman/zfs ] || exit 0

. /usr/share/debconf/confmodule
. /lib/partman/lib/zfs-base.sh

# Only show menu option if there is at least one partition that can be used
# as a ZFS PV
[ $(pv_list_allowed | wc -l) -gt 0 ] || exit 0

db_metaget partman-zfs/text/configure_zfs description

printf "zfs\t%s\n" "$RET"
