#! /bin/sh -e
export LD_LIBRARY_PATH="/target/lib:/target/usr/lib"

. /usr/share/debconf/confmodule
db_subst aboot-installer/bootdev bootdev "$defaultbootdev"
db_input medium aboot-installer/bootdev || true
db_go || true

db_get aboot-installer/bootdev
bootdev=$RET

chroot /target /sbin/e2writeboot $bootdev /boot/bootlx
#chroot /target /usr/bin/touch /boot/grub/menu.lst
#chroot /target /sbin/update-grub

#IMG_CONF=/target/etc/kernel-img.conf
#/target/bin/echo "postinst_hook = /sbin/update-grub" >> $IMG_CONF
#/target/bin/echo "postrm_hook   = /sbin/update-grub" >> $IMG_CONF
#/target/bin/echo "do_bootloader = no" >> $IMG_CONF
