#! /bin/sh

set -e
. /usr/share/debconf/confmodule
#set -x

db_capb backup

log=/var/log/messages

log() {
    logger -t grub-installer "$@"
}

error() {
    log "error: $@"
}

info() {
    log "info: $@"
}

# Make sure mtab in the chroot reflect the currently mounted partitions.
update_mtab() {
    mtab=/target/etc/mtab
    grep /target /proc/mounts | (
	while read devpath mountpoint fstype options n1 n2 ; do
	    devpath=`mapdevfs $devpath || echo $devpath`
	    mountpoint=`echo $mountpoint | sed s%^/target%%`
	    # The sed line remove the mount point for root.
	    if [ -z "$mountpoint" ] ; then
		mountpoint="/"
	    fi
	    echo $devpath $mountpoint $fstype $options $n1 $n2
	done ) > $mtab
}

is_floppy () {
	# FIXME: this is lame, and does not yet support /dev devices.
	echo "$1" | grep -q "\(fd"
}

db_progress START 0 5 grub-installer/progress/title

db_progress INFO grub-installer/progress/step_install

if ! apt-install grub ; then
	info "Calling 'apt-install grub' failed"
	# Hm, unable to install grub into /target/, what should we do?
	db_input critical grub-installer/apt-install-failed || [ $? -eq 30 ]
	if ! db_go; then
		db_progress STOP
		exit 10 # back up to menu
	fi
	db_get grub-installer/apt-install-failed
	if [ true != "$RET" ] ; then
		db_progress STOP
		exit 1
	fi
fi

db_progress STEP 1
db_progress INFO grub-installer/progress/step_bootdev

db_input high grub-installer/bootdev || [ $? -eq 30 ]
if ! db_go; then
	# back up to menu
	db_progress STOP
	exit 10
fi

db_get grub-installer/bootdev
bootdev=$RET

db_progress STEP 1
db_subst grub-installer/progress/step_install_loader BOOTDEV "$bootdev"
db_progress INFO grub-installer/progress/step_install_loader

info "Installing grub on '$bootdev'"

update_mtab

if ! is_floppy "$bootdev"; then
	if chroot /target /sbin/grub-install -h 2>&1 | grep -q no-floppy; then
		info "grub-install support --no-floppy"
		floppyparam="--no-floppy"
	else
		info "grub-install do not support --no-floppy"
	fi
fi

info "Running chroot /target /sbin/grub-install $floppyparam \"$bootdev\""
if chroot /target /sbin/grub-install $floppyparam "$bootdev" >> $log 2>&1 ; then
    info "grub-install ran successfully"
else
    error "Running 'grub-install $floppyparam \"$bootdev\"' failed."
    db_subst grub-installer/grub-install-failed BOOTDEV "$bootdev"
    db_input critical grub-installer/grub-install-failed || [ $? -eq 30 ]
    db_go || true
    db_progress STOP
    exit 1
fi

db_progress STEP 1
db_progress INFO grub-installer/progress/step_config_loader

# Pipe from 'yes' to tell grub to create menu.lst when it is missing A
# better correct fix is to get update-grub to be able to run in
# noninteractive mode.  Newer versions of the grub package support
# '-y' for noninteractive installs.  But we'll keep it as-is for
# Skolelinux.
if chroot /target /usr/bin/yes | chroot /target /sbin/update-grub >> $log 2>&1 ; then
    :
else
    error "Running 'update-grub' failed." 1>&2
    db_input critical grub-installer/update-grub-failed || [ $? -eq 30 ]
    db_go || true
    db_progress STOP
    exit 1
fi

db_progress STEP 1
db_progress INFO grub-installer/progress/step_update_etc

sed -e 's/do_bootloader = yes/do_bootloader = no/' < /target/etc/kernel-img.conf > /target/etc/kernel-img.conf.$$
if [ -z "`grep update-grub /target/etc/kernel-img.conf.$$`" ]; then
    (
      echo "postinst_hook = /sbin/update-grub"
      echo "postrm_hook   = /sbin/update-grub"
    ) >> /target/etc/kernel-img.conf.$$
fi
mv /target/etc/kernel-img.conf.$$ /target/etc/kernel-img.conf

db_progress STEP 1
db_progress STOP
