#!/bin/sh

set -- $1

fs=$1
mp=$2
type=$3
options=$4
dump=$5
pass=$6

log_exec() {
	log-output -t partman-zfs --pass-stdout $* || exit 1
}

case $type in
    zfs)
	if echo "$fs" | grep -Eq '^/'; then
	    # ZVOL
	    log_exec zfs set mountpoint=/${mp#/} ${fs#/dev/zvol/}
	else
	    # ZFS
	    if [ "$mp" = "/var" ]; then
		# NOTE: !!! DANGEROUS !!!
		# /lib/partman/finish.d/20mount_partitions creates '/target/var/{lock,run}'
		# and ZFS don't do overlay mounts by default. And it might not be a
		# good idea to do one here - the mount might (will?) fail at next boot.
		rm -Rvf /target/var
	    fi

	    log_exec zfs set mountpoint=$mp $fs
	    log_exec zfs mount $fs
	fi
	exit 0
	;;
esac

exit 1
