#!/bin/sh

set -- $1

fs=$1
mp=$2
type=$3
options=$4
dump=$5
pass=$6

log_exec() {
	log-output -t partman-zfs --pass-stdout $* || exit 1
}

case $type in
    zfs)
	if echo "$fs" | grep -Eq '^/'; then
	    # ZVOL
	    log_exec zfs set mountpoint=/${mp#/} ${fs#/dev/zvol/}
	else
	    # ZFS
	    [ ! -d "/target/$mp" ] && mkdir -p "/target/$mp"
	    log_exec mount -t zfs $fs /target/$mp
	fi
	exit 0
	;;
esac

exit 1
