import os
Import('env')

Command("Makefile", [], ["cd lib/libumem && ./configure --disable-shared --enable-static"])
Command("libumem.a", [Glob('*.c'),'Makefile',Glob('*.h')], ["cd lib/libumem && make libumem.la && rm -f libumem.a && ln -s .libs/libumem.a"])
if env.GetOption('clean'):
	Execute(Action(["make -C %s distclean" % (os.path.join(env.Dir("#").abspath, 'lib/libumem'))]))
