#!/bin/sh

zfs=no

if test -e /dev/zfs; then
	if [ $(zpool list -H | wc -l) -gt 0 ]; then
		zfs=yes
	fi
fi

if [ "$zfs" = yes ]; then
	apt-install zfsutils || true

	if [ "$(udpkg --print-os)" = "linux" ]; then
	        apt-install zfs-initramfs || true
	fi
fi
