#!/bin/sh

. /lib/partman/lib/base.sh
. /lib/partman/lib/zfs-base.sh

for dev in $DEVICES/*; do
	[ -d $dev ] || continue
	cd $dev
	open_dialog PARTITIONS
	while { read_line num id size type fs path name; [ "$id" ]; }; do
		[ $fs != free ] || continue
		[ -f "$id/method" ] || continue
		[ -f "$id/acting_filesystem" ] || continue
		method=$(cat $id/method)
		filesystem=$(cat $id/acting_filesystem)
		case "$filesystem" in
		    zfs)
			[ -f "$id/mountpoint" ] || continue
			mountpoint=$(cat $id/mountpoint)
			# due to #249322, #255135, #258117:
			if [ "$mountpoint" = /tmp ]; then
				rm -f $id/options/noexec
			fi
			options=$(get_mountoptions $dev $id)
			if [ "$options" = defaults ]; then
				options="rw"
			fi
			echo "${path#/dev/zvol/}" "$mountpoint" zfs $options 0 0
			;;
		esac
	done
	close_dialog
done

local vg lv val mp
for vg in $(vg_list); do
    val=`get_vg_value $vg bootfs`
    if [ "$val" != "unset" ]; then
	for lv in $(lv_list $vg); do
	    val=`get_lv_value $lv mountpoint`
	    if [ "$val" != "unset" ]; then
		if echo "$val" | grep -Eq '^/target'; then
		    mp=`echo "$val/" | sed -e 's/\/target//' -e 's/\/$//'`
		    [ -z "$mp" ] && mp="/"

		    # fs mp type options dump pass
		    echo "$lv $mp zfs - - -"
		fi
	    fi
	done
    fi
done
