#!/bin/sh

[ -f /var/lib/partman/zfs ] || exit 0

. /lib/partman/lib/zfs-base.sh

dev=$1
id=$2

pv_allowed "$dev" "$id" || exit 0

db_metaget partman/method_long/zfs description

printf "zfs\t${RET}\n"
