#!/bin/sh

dev=$1
id=$2
property=$3

[ -f /var/lib/partman/zfs ] || exit 0

case $property in
    formatable)
	echo zfs
	;;
    existing)
	[ -f $id/detected_filesystem ] || exit 0
	fs=$(cat $id/detected_filesystem)

	case "$fs" in
	    zfs)
		echo zfs
		;;
	esac
	;;
esac


